const numberWordsToNumbers = {
    en: {
        zero: 0,
        one: 1,
        two: 2,
        three: 3,
        four: 4,
        five: 5,
        six: 6,
        seven: 7,
        eight: 8,
        nine: 9,
        ten: 10,
        eleven: 11,
        twelve: 12,
        thirteen: 13,
        fourteen: 14,
        fifteen: 15,
        sixteen: 16,
        seventeen: 17,
        eighteen: 18,
        nineteen: 19,
        twenty: 20,
        thirty: 30,
        forty: 40,
        fifty: 50,
        sixty: 60,
        seventy: 70,
        eighty: 80,
        ninety: 90,
        hundred: 100,
        thousand: 1000,
    },
    sv: {
        noll: 0,
        ett: 1,
        två: 2,
        tre: 3,
        fyra: 4,
        fem: 5,
        sex: 6,
        sju: 7,
        åtta: 8,
        nio: 9,
        tio: 10,
        elva: 11,
        tolv: 12,
        tretton: 13,
        fjorton: 14,
        femton: 15,
        sexton: 16,
        sjutton: 17,
        arton: 18,
        nitton: 19,
        tjugo: 20,
        trettio: 30,
        fyrtio: 40,
        femtio: 50,
        sextio: 60,
        sjuttio: 70,
        åttio: 80,
        nittio: 90,
        hundra: 100,
        tusen: 1000,
    },
};

module.exports = numberWordsToNumbers;